### ISSUE TITLE
使用 Excalidraw 做图时

### ISSUE THREAD

**Issue by NashAiomos** [NeutronStarDAO/ICCookBook-English#1]
使用 Excalidraw 做图时：

第一，导出图片尽可能选择 x3 倍的缩放，使图片尽可能清晰，因为点击图片还可以全屏预览，不然放大之后图片太模糊。
第二，导出图片后，也请导出原图数据一起上传到 Github。比如：ic.excalidrawlib 。
第三，请保持图片中字体一致，统一使用 Excalidraw 中的 ”普通“ 字体，而不是 ”手写“ 字体或者 ”代码“ 字体。
第四，辛苦了。

@RyanLee0396

**Comment by RyanLee0396** [comment]
好的 会尽快熟悉 Excalidraw 的操作规范。
之前有一些已完成的英文素材由于作图时卡顿便删除了，请问我要再重新制作一份吗？
相关概念中的 “如何选择共识委员会数量”已经翻译完了，可以审阅一次。

共识层和消息路由层完成初步翻译。 
其中共识层 源码部分，多个小标题那里应该是没有完成？所以英译版没有添加。
消息路由层，从查询/更新调用部分开始没有翻译了(与白皮书内容一致)，编写完毕后可以再提醒我一次。英译版里也添加了 //留言 作为记号。

@NeutronStarPRO

**Comment by NashAiomos** [comment]
辛苦Ryan了，不用再做啦
图片我来处理一下就好，以后注意一下就行

另外就是图片放在一个单独的文件夹里方便管理，文章中的图片路径先使用相对路径链接到文章

消息路由层后面就不用翻译啦

@RyanLee0396 
(*^▽^*) 儿童节快乐
